name: Build, Test and Dockerize Spring Boot App

on:
  push:
    branches: [ master ]  # cambia a "main" si tu rama principal es esa
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysqldb:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: book
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_PASSWORD: 1234
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -p1234"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -u root -p1234 --silent; then
              echo "MySQL is up"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Build with Maven
        run: mvn clean package -DskipTests=false

      - name: Build Docker image
        run: docker build -t springboot-app .
